from turtle import *
s = Screen()
s.bgcolor("black")
pensize(2)
pencolor('red')
def my_goto(x,y):
    penup()
    goto(x,y)
    pendown()
begin_fill()
my_goto(0,-200)
fillcolor('red')
circle(200)
end_fill()
begin_fill()
pencolor('white smoke')
fillcolor('white smoke')
my_goto(0,-170)
circle(170)
end_fill()
begin_fill()
my_goto(0,-130)
pencolor('red')
fillcolor('red')
circle(130)
end_fill()
begin_fill()
my_goto(0,-100)
pencolor('medium blue')
fillcolor('medium blue')
circle(100)
end_fill()
begin_fill()
my_goto(90,30)
pencolor('white smoke')
fillcolor('white smoke')
for i in range(5):
    rt(144)
    fd(183)
end_fill()
